DO_NOT_REVIEW: Stackedbar series
mattapperson/eui pull request #1
Opened 2018-05-29 17:04 UTC by markov00

This PR is on hold. Waiting for new Bar/Rect components PR https://github.com/mattapperson/eui/pull/2
This PR provides the feature creating stacked bar charts. 

General todos:
- [x] Add `stackBy` props to XYChart
- [x] Fix Bar `strokeWidth` to 0 to avoid bars overlapping
- [x] Update the js example code
- [x] Fix crosshair values using y0 values on stacked bars
- [ ] Order properly the crosshair label depending on the stack visual order
- [ ] Add horizontally stacked bar example
- [ ] To stack properly react-vis expects each x value in each series to be present https://uber.github.io/react-vis/documentation/api-reference/xy-plot
- [x] Check if `stackBy` applies also to area charts (yes but I will open a new PR for area charts)

2018-06-14 13:59 UTC, mattapperson requested changes

2018-06-14 13:59 UTC, mattapperson commented on src/components/xy_chart/chart.js
> +    return chartDataForXValue
This is a very expensive thing to do as a mouse moves. Would love to discuss why this is needed here

2018-06-14 13:59 UTC, mattapperson commented on src/components/xy_chart/chart.js
> +  stackBy: PropTypes.string,
we should really provide a default prop for this too I think

2018-06-19 11:04 UTC, markov00 commented
I'm closing this PR in favour of https://github.com/mattapperson/eui/pull/2 that fix crosshairs, add vertical and horizontal components, barcharts and histograms.

2018-06-19 11:04 UTC, closed without merging